chore: add fees documentation
sygmaprotocol/sygma-fee-oracle pull request #36
Opened 2023-03-01 17:05 UTC by MakMuftic

One of the PRs related to adding fee-handling documentation across all services.

## Description

- Add basic structure of `/docs` folder
- Add partial Home page for fee oracle technical documentation
- Add fee estimate message technical documentation

## Related Issue Or Context

Related to [#106](https://github.com/sygmaprotocol/project-backlog/issues/106)

## How Has This Been Tested? Testing details.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Documentation

## Checklist:

- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have ensured that all acceptance criteria (or expected behavior) from issue are met
- [ ] I have updated the documentation locally and in docs.
- [ ] I have added tests to cover my changes.
- [ ] I have ensured that all the checks are passing and green, I've signed the CLA bot

2023-03-03 11:54 UTC, nmlinaric approved these changes

2023-03-09 19:23 UTC, P1sar approved these changes

2023-03-13 13:22 UTC, P1sar requested changes

2023-03-13 13:22 UTC, P1sar commented on docs/Home.md
> +- **msgGasLimit** - the maximum amount of gas units that can be used on execution
This is a hardcoded value? Or it is taken from the config? IF it is then by what param?

2023-03-21 18:42 UTC, P1sar approved these changes

2023-03-21 18:42 UTC, merged